
// automatically generated by m4 from headers in proto subdir


#ifndef __SYS_COMPILER_H__
#define __SYS_COMPILER_H__


#if defined(__CLION_IDE__) | defined(__INTELLISENSE__)

#define __LIB__
#define __SMALLC
#define __SAVEFRAME__
#define __z88dk_fastcall
#define __FASTCALL__
#define __CALLEE__
#define __SCCZ80
#define __Z80
#define __naked
#define __z88dk_callee
#define __stdc
#define __smallc
#define __smallconly
#define __preserves_regs
#define __no_z88dk_declspec
#define __at(x)
#define __sfr
#define __vasmallc

#else

/* Temporary fix to turn off features not supported by sdcc */
#if __SDCC | __clang__
#define __LIB__
#define __SAVEFRAME__
#define __SMALLC
#define far
#define __vasmallc
#define __Z88DK_R2L_CALLING_CONVENTION 1
#define __stdc
#define __z88dk_deprecated
#define __z88dk_sdccdecl

#if __SDCC
// __smallconly is for functions that only come in a smallc variant
#define __smallconly __smallc
#else
// Clang - we're out of luck
#define __smallconly
#endif

// Make intellisense run easier..
#if __clang__ | __CLANG
#define __STDC_ABI_ONLY
#if defined(__LLVMZ80)
// ravn/llvm-z80 clang honours the z88dk / SDCC calling conventions via real
// function attributes (the same mapping as the classic sys/compiler.h): the
// newlib workers are the sdcc_ix build, so __smallc == sdcccall(0) (stack args,
// caller-clean, i16 return in HL), __z88dk_callee == z80_callee (stack args,
// callee-clean), __z88dk_fastcall == z80_fastcall (single arg in L/HL/DE:HL by
// width).  Without these the attributes are no-ops and clang uses its default
// sdcccall(1) (HL/DE args, DE return) -> the worker and clang disagree on the
// ABI and, e.g., a qsort comparator scrambles the array.
//
// GATED ON __LLVMZ80, not bare __clang__: ez80-clang ALSO defines __clang__ /
// __CLANG (it is a clang fork too) but is __stdc / HL-return already and may
// not support sdcccall -- it must keep the plain no-op mapping in the #else.
#define __smallc __attribute__((sdcccall(0)))
#define __z88dk_callee __attribute__((z80_callee))
#define __z88dk_fastcall __attribute__((z80_fastcall))
// The variadic stdio family returns its count in HL (classic clib convention);
// declaring it __smallc == sdcccall(0) makes clang read the return from HL.
#undef  __vasmallc
#define __vasmallc __smallc
#else
// ez80-clang (and any other __clang__|__CLANG that is not __LLVMZ80): keep the
// conventions as no-ops -- it uses the __stdc ABI and must not be given the
// llvmz80 sdcccall/z80_callee/z80_fastcall attributes.
#define __smallc
#define __z88dk_callee
#define __z88dk_fastcall
#endif
// SDCC parses __preserves_regs as a real function attribute; clang has no
// such attribute, so without a macro it is left as a literal token
// followed by an argument list after preprocessing, which clang's parser
// then sees as garbage after the function declarator (a string dot h
// declaration ends up as "extern char *foo(...) (d,e);", which fails as
// "expected function body after function declarator").  Defining it as a
// no-op function-like macro (matching sys slash compiler dot h's existing
// clang-safe definition) strips it before clang ever sees it.  (Written
// with dots/slashes spelled out to avoid m4 misinterpreting path-like
// tokens in this generated-header comment.)
#define __preserves_regs(x...)
#endif

#else
// sccz80 case
#define __SMALLC __smallc
#define __smallconly __smallc
#define __vasmallc __smallc
#define __z88dk_deprecated
#endif

#endif

#ifdef __8080
#define __DISABLE_BUILTIN
#endif

#ifdef __8085
#define __DISABLE_BUILTIN
#endif

#if __SDCC && __GBZ80
#define __DISABLE_BUILTIN
#define __z88dk_fastcall
#endif

#define NONBANKED __nonbanked
#define BANKED __banked

#define __CHAR_LF '\n'
#define __CHAR_CR '\r'


#endif
